import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

/**
 * Generated class for the WorkOutMenusAddPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-work-out-menus-add',
  templateUrl: 'work-out-menus-add.html',
})
export class WorkOutMenusAddPage {

  constructor(public navCtrl: NavController, public navParams: NavParams) { }

  ionViewDidLoad() {
    console.log('ionViewDidLoad WorkOutMenusAddPage');
  }
  public static getAllWorkOutMenus(lang) {
    var menus = [
      { workOutId: 'abductor' },
      { workOutId: 'abWheelRollout' },
      { workOutId: 'aductor', workOutName: 'Aductor' },
      { workOutId: 'armCurl', workOutName: 'Arm Curl' },
      { workOutId: 'armHighSitUp' },
      { workOutId: 'backExtension', workOutName: 'Back Extension' },
      { workOutId: 'backPlank' },
      { workOutId: 'barbellCurl', workOutName: 'Barbell Curl' },
      { workOutId: 'barbellOverHeadPress' },
      { workOutId: 'BarbellRussianTwist' },
      { workOutId: 'barbellShoulderPress' },
      { workOutId: 'barbellShrug', workOutName: 'Barbell Shrug' },
      { workOutId: 'barbellSpiderCurl', workOutName: 'Barbell Spider Curl' },
      { workOutId: 'behindNeckLatPullDown', workOutName: 'Behind Neck Lat Pull Down' },
      { workOutId: 'benchDips', workOutName: 'Bench Dips' },
      { workOutId: 'benchPress', workOutName: 'Bench Press' },
      { workOutId: 'bentOverBarbellRow', workOutName: 'Bent Over Barbell Row' },
      { workOutId: 'bentOverDumbbellRow', workOutName: 'Bent Over Dumbbell Row' },
      { workOutId: 'bulgarianSplitSquat', workOutName: 'Bulgarian Split Squat' },
      { workOutId: 'cableCrossover', workOutName: 'Cable Crossover' },
      { workOutId: 'CableCrunch' },
      { workOutId: 'cableCurl', workOutName: 'Cable Curl' },
      { workOutId: 'cableDragCurl', workOutName: 'Cable Drag Curl' },
      { workOutId: 'cableFly', workOutName: 'Cable Fly' },
      { workOutId: 'cableHammerCurl', workOutName: 'Cable Hammer Curl' },
      { workOutId: 'cableKickback', workOutName: 'Cable Kickback' },
      { workOutId: 'cableRopeOverheadTricepsExtension', workOutName: 'Cable Rope Overhead Triceps Extension' },
      { workOutId: 'cableTricepsExtension', workOutName: 'Cable Triceps Extension' },
      { workOutId: 'calfPress', workOutName: 'Calf Press' },
      { workOutId: 'chestPress', workOutName: 'Chest Press' },
      { workOutId: 'chinUp', workOutName: 'Chin up' },
      { workOutId: 'chinning' },
      { workOutId: 'closeGripBenchPress', workOutName: 'Close Grip Bench Press' },
      { workOutId: 'concentrationCurl', workOutName: 'Concentration Curl' },
      { workOutId: 'concentrationHammerCurl', workOutName: 'Concentration Hammer Curl' },
      { workOutId: 'Crunch' },
      { workOutId: 'deadLift', workOutName: 'Dead Lift' },
      { workOutId: 'declineBenchPress', workOutName: 'Decline Bench Press' },
      { workOutId: 'declineChestPress', workOutName: 'Decline Chest Press' },
      { workOutId: 'declineDumbbellFly', workOutName: 'Decline Dumbbell Fly' },
      { workOutId: 'declineDumbbellPress', workOutName: 'Decline Dumbbell Press' },
      { workOutId: 'dips', workOutName: 'Dips' },
      { workOutId: 'dragCurl', workOutName: 'Drag Curl' },
      { workOutId: 'dumbbellCurl', workOutName: 'Dumbbell Curl' },
      { workOutId: 'dumbbellFly', workOutName: 'Dumbbell Fly' },
      { workOutId: 'dumbbellKickback', workOutName: 'Dumbbell Kickback' },
      { workOutId: 'dumbbellPress', workOutName: 'Dumbbell Press' },
      { workOutId: 'dumbbellPullover', workOutName: 'Dumbbell Pullover' },
      { workOutId: 'dumbbellShoulderPress' },
      { workOutId: 'dumbbellShrug', workOutName: 'Dumbbell Shrug' },
      { workOutId: 'dumbbellSpiderCurl', workOutName: 'Dumbbell Spider Curl' },
      { workOutId: 'dumbbellSquat', workOutName: 'Dumbbell Squat' },
      { workOutId: 'dumbbellTricepsExtension', workOutName: 'Dumbbell Triceps Extension' },
      { workOutId: 'frontSquat', workOutName: 'Front Squat' },
      { workOutId: 'gobletSquat', workOutName: 'Goblet Squat' },
      { workOutId: 'hammerCurl', workOutName: 'Hammer Curl' },
      { workOutId: 'HangingKneeRaise' },
      { workOutId: 'HangingLegRaise' },
      { workOutId: 'HangingPike' },
      { workOutId: 'HangingRotatedPike' },
      { workOutId: 'HangingRotatedKneeRaise' },
      { workOutId: 'hipThrust', workOutName: 'Hip Thrust' },
      { workOutId: 'inclineBenchPress', workOutName: 'Incline Bench Press' },
      { workOutId: 'inclineChestPress', workOutName: 'Incline Chest Press' },
      { workOutId: 'inclineDumbbellCurl', workOutName: 'Incline Dumbbell Curl' },
      { workOutId: 'inclineDumbbellFly', workOutName: 'Incline Dumbbell Fly' },
      { workOutId: 'inclineDumbbellPress', workOutName: 'Incline Dumbbell Press' },
      { workOutId: 'inclineHammerCurl', workOutName: 'Incline Hammer Curl' },
      { workOutId: 'invertedRow', workOutName: 'Inverted Row' },
      { workOutId: 'latPullDown', workOutName: 'Lat Pull Down' },
      { workOutId: 'legExtension', workOutName: 'Leg Extension' },
      { workOutId: 'legPress', workOutName: 'Leg Press' },
      { workOutId: 'LegRaise', workOutName: 'Leg Press' },
      { workOutId: 'lunge', workOutName: 'Lunge' },
      { workOutId: 'lyingDumbbellTricepsExtension', workOutName: 'Lying Dumbbell Triceps Extension' },
      { workOutId: 'lyingTricepsExtension', workOutName: 'Lying Triceps Extension' },
      { workOutId: 'multiHip', workOutName: 'Multi Hip' },
      { workOutId: 'one-armDumbbellTricepsExtension', workOutName: 'One Arm Dumbbell Triceps Extension' },
      { workOutId: 'oneArmCableKickback', workOutName: 'One Arm Cable Kickback' },
      { workOutId: 'oneArmCableTricepsExtension', workOutName: 'One Arm Cable Triceps Extension' },
      { workOutId: 'oneArmDumbbellRow', workOutName: 'One Arm Dumbbell Row' },
      { workOutId: 'oneArmLyingTricepsExtension', workOutName: 'One Arm Lying Triceps Extension' },
      { workOutId: 'pecDeckFly', workOutName: 'Pec Dec Fly' },
      { workOutId: 'Plank' },
      { workOutId: 'preacherCurl', workOutName: 'Preacher Curl' },
      { workOutId: 'pullUp', workOutName: 'Pull Up' },
      { workOutId: 'pushUp', workOutName: 'Push Up' },
      { workOutId: 'reverseGripLatPullDown', workOutName: 'Reverse Grip Lat Pull Down' },
      { workOutId: 'reverseGripStandingCableRow', workOutName: 'Reverse Grip Standing Cable Row' },
      { workOutId: 'reverseGripTricepsPressDown', workOutName: 'Reverse Grip Triceps Press Down' },
      { workOutId: 'rowPulleyCableCrossover', workOutName: 'Row Pulley Cable Crossover' },
      { workOutId: 'RussianTwist' },
      { workOutId: 'seatedCableRow', workOutName: 'Seated Cable Row' },
      { workOutId: 'seatedLegCurl', workOutName: 'Seated Leg Curl' },
      { workOutId: 'SideBends' },
      { workOutId: 'sideLateralRaise' },
      { workOutId: 'SideLegRaise' },
      { workOutId: 'sidePlank' },
      { workOutId: 'SitUp' },
      { workOutId: 'SitUpTwist' },
      { workOutId: 'smithMachineBenchPress', workOutName: 'Smith Machine Bench Press' },
      { workOutId: 'smithMachineInclineBenchPress', workOutName: 'Smith Machine Incline Bench Press' },
      { workOutId: 'smithMachineSeatedCalfRaise', workOutName: 'Smith Machine Seated Calf Raise' },
      { workOutId: 'smithMachineShrug', workOutName: 'Smith Machine Shrug' },
      { workOutId: 'smithMachineStandingCalfRaise', workOutName: 'Smith Machine Standing Calf Raise' },
      { workOutId: 'squat', workOutName: 'Squat' },
      { workOutId: 'standingCableRow', workOutName: 'Standing Cable Row' },
      { workOutId: 'stiffLegDeadlift', workOutName: 'Stiff Leg Deadlift' },
      { workOutId: 'straightArmPullDown', workOutName: 'Straight Arm Pull Down' },
      { workOutId: 'SupermanPike' },
      { workOutId: 't-barRow', workOutName: 'T-Bar Row' },
      { workOutId: 'tricepsDips', workOutName: 'Triceps Dips' },
      { workOutId: 'tricepsPressDown', workOutName: 'Triceps Press Down' },
      { workOutId: 'tricepsPressDownCableRope', workOutName: 'Triceps Press Down Cable Rope' },
      { workOutId: 'wristCurl', workOutName: 'Wrist Curl' },
      { workOutId: 'wristExtension', workOutName: 'Wrist Extension' }
    ];
    return menus;
  }
}
